<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMzMC7QM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMzMC7QM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMzMC7QM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMzMC7QM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMzMC7QM\App_KernelDevDebugContainer([
    'container.build_hash' => 'MzMC7QM',
    'container.build_id' => '17003bae',
    'container.build_time' => 1589214155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMzMC7QM');
